on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
name: "Flatpak X11"
permissions:
  id-token: write
  contents: read
jobs:
  flatpak-x11:
    name: "Flatpak X11"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: io.github.nokse22.Exhibit.flatpak
        manifest-path: io.github.nokse22.Exhibit.json
        cache-key: flatpak-builder-${{ github.sha }}